Strongly typed query rows
scylladb/scylla-rust-driver pull request #101
Opened 2020-11-08 01:40 UTC by cvybhu

This PR implements a way to parse rows returned by Session::query as strongly typed tuples or custom types.
For example:
```rust
    // Rows can be parsed as tuples
    if let Some(rows) = session.query("SELECT a, b, c FROM ks.t", &[]).await? {
        for (a, b, c) in rows.into_typed::<(i32, i32, String)>() {
            println!("a, b, c: {}, {}, {}", a, b, c);
        }
    }

    // Or as custom structs that derive FromRow
    #[derive(Debug, FromRow)]
    struct RowData {
        a: i32,
        b: Option<i32>,
        c: String,
    }

    if let Some(rows) = session.query("SELECT a, b, c FROM ks.t", &[]).await? {
        for row_data in rows.into_typed::<RowData>() {
            println!("row_data: {:?}", row_data);
        }
    }
```
API proposed in #99 turned out very verbose because each `SELECT` required specifying returned row type (Rust has no default generic arguments) and there were some additional issues with `impl Into<Query>`  when trying to explicitly define generic arguments.

This solution implements 
```rust
Vec::<Row>::into_typed::<RowT: From<Row>>(self) -> impl Iterator<Item = RowT> {
    self.into_iter().map(RowT::from)
}
```
to allow converting Vec<Row> into iterator of strongly typed rows

2020-11-08 01:53 UTC, cvybhu commented
@psarna @piodul could you review

2020-11-08 09:38 UTC, piodul requested changes
Left some comments, but I think I like the overall approach.

There is one more place that needs some changes, which I forgot to mention that in the issue description (sorry about that). We have an additional API for querying rows, which returns an asynchronous iterator (a [stream](https://docs.rs/futures/0.3.7/futures/stream/trait.Stream.html)). This API uses paging, so it's more efficient for queries which return large numbers of rows.

Please add a corresponding `into_typed` method to the [`QueryIterator`](https://github.com/scylladb/scylla-rust-driver/blob/main/scylla/src/transport/iterator.rs#L22). Note that this function will have to return a stream, not an iterator.

2020-11-08 09:38 UTC, piodul commented on scylla-macros/src/lib.rs
> +                                || panic!("Row too short to convert to {}!", stringify!(#struct_name)))
We should rather return an error, not panic here.

2020-11-09 00:04 UTC, cvybhu commented
Okay requested changes done. I edited these commits so they compile, sorry about that. 
Now we have to unwrap each row manually so probably the api could be made simpler by just implementing `Row::into_typed<RowT>(self) -> Result<RowT>`
Current api:
```rust
if let Some(rows) = session.query("SELECT a, b, c FROM ks.t", &[]).await? {
    for row in rows.into_typed::<(i32, i32, String)>() {
        let (a, b, c) = row ?;
        println!("a, b, c: {}, {}, {}", a, b, c);
    }
}
```
With simpler:
```rust
if let Some(rows) = session.query("SELECT a, b, c FROM ks.t", &[]).await? {
    for row in rows {
        let (a, b, c) = row.into_typed::<(i32, i32, String)>() ?;
        println!("a, b, c: {}, {}, {}", a, b, c);
    }
}
```
Then there would be no need for any custom iterators/streams which would make it more readable.
I'm going to implement it and see if there are any problems

2020-11-09 01:38 UTC, cvybhu commented
Okay all done, @piodul could you take a look?

2020-11-09 14:40 UTC, psarna commented
@cvybhu the code looks good in general, but we actually want to use the fact that for a given query, all rows are returned with the same type. So that instead of casting each row separately like here:
```rust
if let Some(rows) = session.query("SELECT a, b, c FROM ks.t", &[]).await? {
    for row in rows {
        let (a, b, c) = row.into_typed::<(i32, i32, String)>() ?;
        println!("a, b, c: {}, {}, {}", a, b, c);
    }
}
```
we'd rather just do something like:
```rust
if let Some(rows) = session.query::<(i32, i32, String)>("SELECT a, b, c FROM ks.t", &[]).await? {
    for (a, b, c) in rows {
        println!("a, b, c: {}, {}, {}", a, b, c);
    }
}
```

given that you have most of the code ready, this change should probably be quite easy to do, if I'm not mistaken.

2020-11-09 14:48 UTC, piodul commented
@cvybhu Just one thing I'd like to add - if we go with the interface proposed by @psarna, we would move the existing, untyped interface to methods like `query_untyped`, `execute_untyped`.

2020-11-09 15:33 UTC, cvybhu commented
It would be the easiest to add back `into_typed` for iterators/streams, the code for this is already commited.
I feel like this api is more intuitive than `query_untyped` and `query_typed` - here the user has one simple option to perform a query and can start worrying about interpreting rows after receiving the rows. With `query_untyped` and `query_typed` user that wants to perform an insert has to read into documentation to learn about differences between these two options.

And we could maybe leave `Row::into_typed` - maybe someone would like to do something strange with 4th column's value and then cast first three columns to a tuple or something like that.

For now I'm gonna bring back `into_typed` for iterators/streams

2020-11-09 16:04 UTC, cvybhu commented
Alright done

2020-11-09 16:08 UTC, psarna commented
Good enough for me. The users are likely to always use the typed version, but we can address that later, the interface is already much better than before. @piodul feel free to merge if you also ack the changes.

2020-11-09 16:28 UTC, piodul approved these changes
LGTM

2020-11-09 16:29 UTC, merged