Parametrize `Deserialize{Value,Row}` with two lifetimes: `'frame` and `'metadata` separately
scylladb/scylla-rust-driver pull request #1101
Opened 2024-10-21 19:57 UTC by wprzytula

Refs: #462

## Tl;dr
A second lifetime parameter is introduced to entities comprising the bottom part of the new deserialization framework: `'metadata`.

## Deserialization traits - recap

`DeserializeValue` requires two types of data in order to perform deserialization:
1) a reference to the CQL frame (a `FrameSlice`),
2) the type of the column being deserialized, being part of the result metadata.

Similarly, `DeserializeRow` requires two types of data in order to perform deserialization:
1) a reference to the CQL frame (a `FrameSlice`),
2) a slice of specifications of all columns in the row, being part of the result metadata.

### Observation

When deserializing owned types, both the frame and the metadata can have any lifetime and it's not important. When deserializing borrowed types, however, they borrow from the frame, so their lifetime must necessarily be bound by the lifetime of the frame. Metadata is only needed for the deserialization, so its lifetime does not abstractly bound the deserialized value.

### Problem

Up to this PR, `Deserialize{Value, Row}` were only parametrized by one lifetime: `'frame`, which bounded both the frame slice and the metadata. This was done that way due to an assumption that both the metadata and the frame (shared using `Bytes`) will be owned by the same entity. However, the new idea of deserializing result metadata to a borrowed form (to save allocations) makes result metadata's lifetime shorter than the frame's lifetime.

### Implemented solution

Not to unnecessarily shorten the deserialized values' lifetime, a separate lifetime parameter is introduced for result metadata: `'metadata`.

The PR is large, but the changes are mostly mechanical, by adding
the second lifetime parameter.

## Pre-review checklist

- [x] I have split my patch into logically separate commits.
- [x] All commit messages clearly explain what they change and why.
- ~~[ ] I added relevant tests for new features and bug fixes.~~
- [x] All commits compile, pass static checks and pass test.
- [x] PR description sums up the changes and reasons why they should be introduced.
- ~~[ ] I have provided docstrings for the public items that I want to introduce.~~
- [ ] I have adjusted the documentation in `./docs/source/`. <-- _not yet, will be done at the end of the deserialization refactor_
- ~~[ ] I added appropriate `Fixes:` annotations to PR description.~~

2024-10-21 20:07 UTC, wprzytula commented
> `cargo semver-checks` found no API-breaking changes in this PR! 🎉🥳 Checked commit: [4406db5](https://github.com/scylladb/scylla-rust-driver/commit/4406db55710c161a35188629bfe348e38e9eafa6)

???

This looks like a crude bug... Adding a new lifetime parameter to a trait necessarily breaks the API, in the simplest possible way: syntactically.

2024-10-22 10:51 UTC, muzarski approved these changes
LGTM. Great explanation of why we need to introduce second lifetime parameter, so the review went smoothly

2024-10-22 10:51 UTC, muzarski commented on scylla-cql/src/types/deserialize/value.rs
> +);
The old odd formatting got fixed. Nice!

2024-10-22 10:51 UTC, muzarski commented on scylla-cql/src/types/deserialize/value.rs
> +>,
The formatter going crazy again

2024-10-24 09:35 UTC, Lorak-mmk commented
> Refs: #462
> ## Tl;dr
> 
> A second lifetime parameter is introduced to entities comprising the bottom part of the new deserialization framework: `'metadata`.
> ## Deserialization traits - recap
> 
> `DeserializeValue` requires two types of data in order to perform deserialization:
> 
>     1. a reference to the CQL frame (a `FrameSlice`),
> 
>     2. the type of the column being deserialized, being part of the result metadata.
> 
> 
> Similarly, `DeserializeRow` requires two types of data in order to perform deserialization:
> 
>     1. a reference to the CQL frame (a `FrameSlice`),
> 
>     2. a slice of specifications of all columns in the row, being part of the result metadata.
> 
> 
> ### Observation
> 
> When deserializing owned types, both the frame and the metadata can have any lifetime and it's not important. When deserializing borrowed types, however, they borrow from the frame, so their lifetime must necessarily be bound by the lifetime of the frame. Metadata is only needed for the deserialization, so its lifetime does not abstractly bound the deserialized value.

If that were the case then there would be no need to introduce second lifetime to those traits, you could just use anonymous lifetime / have a lifetime-generic method:
```
    fn deserialize(
        typ: &ColumnType,
        v: Option<FrameSlice<'frame>>,
    ) -> Result<Self, DeserializationError>;
```

The reason that seems not possible it precisely that deserialized values are bound by metadata lifetime, for example a `ListlikeIterator`.

This sentence confused me so much that I had to go and try to do this change (and learn why it is not possible) in order to understand why this PR introduces the second lifetime. 
Please fix the sentence.

> ### Problem
> 
> Up to this PR, `Deserialize{Value, Row}` were only parametrized by one lifetime: `'frame`, which bounded both the frame slice and the metadata. This was done that way due to an assumption that both the metadata and the frame (shared using `Bytes`) will be owned by the same entity. However, the new idea of deserializing result metadata to a borrowed form (to save allocations) makes result metadata's lifetime shorter than the frame's lifetime.
> ### Implemented solution
> 
> Not to unnecessarily shorten the deserialized values' lifetime, a separate lifetime parameter is introduced for result metadata: `'metadata`.
> 
> The PR is large, but the changes are mostly mechanical, by adding the second lifetime parameter.

2024-10-24 10:08 UTC, Lorak-mmk requested changes
Suggestion: such change should have new tests, right? Those should showcase usage with 2 different lifetimes.

2024-10-25 10:02 UTC, wprzytula commented
v1.1: addressed comments.

2024-10-25 11:37 UTC, Lorak-mmk approved these changes

2024-10-26 19:38 UTC, merged