Add `flatten` attribute to derive SerializeRow
scylladb/scylla-rust-driver pull request #1144
Opened 2024-12-07 09:32 UTC by nrxus

This is similar to the `flatten` attribute in [serde](https://serde.rs/attr-flatten.html). 

For now I've only added support when using `match_by_name` flavor, largely because that's the way I am using scylla. I'd assume that extending it to support the `enforce_ordering` flavor would actually be easier but it might also need new traits similar to how I had to add some for `match_by_name`. Both the parent struct and the flattened struct need to be `match_by_name`, if the parent struct isn't then there is a clear compiler error, if the flattened struct isn't then there is also a compiler error but it'd be a little more opaque because it'd be produced by lack of implementation of a doc hidden trait. If this was ever extended to `enforce_ordering`, then it will also work similarly that you cannot mix and match flavors when flattening. 

I have only added this attribute to `SerializeRow` because it was easier than `DeserializeRow` but I also want to add it to that macro in a future PR next chance I get to dig into this code. However, I have done enough digging to know that implementing this attribute on `DeserializeRow` will require a breaking change in the `DeserializeRow` *trait*. Realistically I doubt many people are manually implementing that trait so I don't think it'd actually be a breaking change in practice, but by semver rules alone it would be. 

All the new traits/structs/enums needed for this change are marked as `#[doc(hidden)]` to prevent leaking the API too early in case we want to change some stuff, so for now it will just be an implementation detail of what the macro creates. 

For context, I am currently dealing with an issue that if I have different insert queries where one sets N columns and another one sets the same N and one extra, then I have two make two structs with N repeated fields. With this PR I'd be able to to instead flatten the struct with N fields inside the other struct to make my code more maintainable. 

## Pre-review checklist

- [X] I have split my patch into logically separate commits.
- [X] All commit messages clearly explain what they change and why.
- [X] I added relevant tests for new features and bug fixes.
- [X] All commits compile, pass static checks and pass test.
- [X] PR description sums up the changes and reasons why they should be introduced.
- [X] I have provided docstrings for the public items that I want to introduce.

2024-12-09 18:21 UTC, nrxus commented
I apologize about the multiple force pushes yesterday, I was chewing on it yesterday a bit more since it wasn't reviewed yet and decided to move some stuff around to make it more clear that all the new structs are internal to the macro implementation only (by moving it to that sub-module). All that should be done by now. 

I have also started work on adding the flatten attribute for the `enforce_order` flavor as well but in a separate branch. Let me know if you have a preference on whether to put that as its own PR or push it here so that the entire support for `#[flatten]` for `SerializeRow` is all on in one PR.

2024-12-12 02:53 UTC, nrxus commented
@wprzytula would you mind taking a look at this PR and tell me if you would like me to keep it as-is or add the flatten support to the `enforced_order` flavor as well in this PR?

2024-12-17 21:07 UTC, nrxus commented
@Lorak-mmk , could you take a look and let me know if there are any concerns holding this PR?

2024-12-18 17:36 UTC, wprzytula commented
@nrxus We're sorry for poor responsivity on our side. We're busy with next year planning; we'll be able to look at your PR later.

2024-12-18 18:27 UTC, Lorak-mmk commented
This is a significant but breaking change, so we most likely won't be able to attend to it before releasing 1.0. We are quite busy with other work :(

2024-12-18 20:07 UTC, nrxus commented
I made especially sure not to change any existing API, and to hide all of the new types/traits in the existing internal module to not increase the public API surface area other the new attribute.

2024-12-18 20:15 UTC, nrxus commented
> > I made especially sure not to change any existing API, and to hide all of the new types/traits in the existing internal module to not increase the public API surface area other the new attribute.
> 
> In such case, we will technically be able to release it in, say, 1.1, when we find time to review and accept this after we release 1.0. Does it sound OK to you, @nrxus ?

Yep sounds good! I'll just keep pointing to my branch for now. I also have a branch to do this same support but when serializing with order enforced. Should I just merge it here so you all only have to review it as one complete feature? It'd make the overall size of the PR bigger which is why I had kept it separate

2024-12-18 20:23 UTC, wprzytula commented
> > > I made especially sure not to change any existing API, and to hide all of the new types/traits in the existing internal module to not increase the public API surface area other the new attribute.
> > 
> > 
> > In such case, we will technically be able to release it in, say, 1.1, when we find time to review and accept this after we release 1.0. Does it sound OK to you, @nrxus ?
> 
> Yep sounds good! I'll just keep pointing to my branch for now. I also have a branch to do this same support but when serializing with order enforced. Should I just merge it here so you all only have to review it as one complete feature? It'd make the overall size of the PR bigger which is why I had kept it separate

IMO let's have it in a single PR, separate commits.

2024-12-18 20:27 UTC, Lorak-mmk commented
> > This is a significant but breaking change, so we most likely won't be able to attend to it before releasing 1.0. We are quite busy with other work :(
> 
> Are you sure? `semver-checks` disagrees with you:
> 
> > `cargo semver-checks` found no API-breaking changes in this PR! 🎉🥳 Checked commit: [4184a7b](https://github.com/scylladb/scylla-rust-driver/commit/4184a7b1174baecea1845a36377ef8556317b046)

I made a typo. I definitely meant that this is NOT a breaking change, and thus we will not prioritise the review before releasing 1.0.

2025-03-04 22:41 UTC, nrxus commented
@Lorak-mmk congrats on the v1.0 release! 🎉 . I have rebased this PR against the `main` branch so it should be good to be reviewed whenever

2025-03-11 17:42 UTC, blablacio commented
This looks really useful, but wondering if the flatten attribute can also be added to derive SerializeValue, which I'm using for a bunch of UDTs I have in my app?

I have a struct that's used independently in some parts of my code, which I include in my main struct that essentially derives SerializeValue in order to implement a UDT.

2025-03-13 07:03 UTC, wprzytula requested changes
:rocket: :tada: :crab:
This is one of the highest quality external contributions I've ever reviewed!
Great job!

2025-03-13 07:03 UTC, wprzytula commented on scylla-macros/src/serialize/row.rs
> +                }));
:question: I feel this commit requires a more comprehensive explanation in the commit message. An example there and here in a comment would definitely help, too.

2025-03-13 07:03 UTC, wprzytula commented on scylla-macros/src/serialize/row.rs
> +                writer: &mut #crate_path::RowWriter<'_scylla_ser_row_writer_buffer>,
:100: It's shocking that we wrote it this way. Thanks for spotting the problem!

2025-03-16 20:03 UTC, nrxus commented on scylla-cql/src/lib.rs
> +            ) -> Result<WrittenCellProof<'b>, SerializationError> {
We definitely can but it doesn't seem worth? The function is pretty small, with most of it being inside the `map_err` closure so we could always make a private function for that one if you want.

2025-03-16 20:27 UTC, nrxus commented on scylla-cql/src/lib.rs
> +            ) -> Result<WrittenCellProof<'b>, SerializationError> {
FWIW this function is basically just extracting code that was manually written inside the macro code (and hence added to code bloat anyway but at macro expansion time). 

Some of the declarative macros also could probably be simplified by using this function. See:

https://github.com/scylladb/scylla-rust-driver/blob/6be8877f704b28e0f729288c0dc74524a96c032d/scylla-cql/src/serialize/row.rs#L134-L142

https://github.com/scylladb/scylla-rust-driver/blob/6be8877f704b28e0f729288c0dc74524a96c032d/scylla-cql/src/serialize/row.rs#L200-L208

https://github.com/scylladb/scylla-rust-driver/blob/6be8877f704b28e0f729288c0dc74524a96c032d/scylla-cql/src/serialize/row.rs#L289-L294

All of these could be "simplified" with this new function.

2025-03-16 20:31 UTC, nrxus commented on scylla-macros/src/serialize/row.rs
> +    flatten: bool,
I've re-worded this comment to try to be more clear. The field is serialized using `SeriallizeRow` is what I meant, and any columns that get serialized as part of that process get flattened into this parent struct.

2025-03-16 20:38 UTC, nrxus commented on scylla-macros/src/serialize/row.rs
> +        let unflattened_tys: Vec<_> = unflattened.iter().map(|f| &f.ty).collect();
Actually no, I tried and they all need the `Vec<_>`

2025-03-16 20:44 UTC, nrxus commented on scylla-macros/src/serialize/row.rs
> +        };
FWIW the allocation should only be done once (per serialization) since I am inserting all fields at once, not one by one. If the concern is the slow hash during look-up then we could try to use a faster hash. But I am open to whatever you all decide.

2025-03-16 20:55 UTC, nrxus commented on scylla-cql/src/lib.rs
> +                    value: &impl SerializeValue,
Adding the indirection of `&dyn` doesn't seem to give us much, instead I split  most of this generic function into a private function such that during monomorphization there isn't much to duplicate. Let me know if you think that's enough.

2025-03-16 21:10 UTC, nrxus commented on scylla-macros/src/serialize/row.rs
> +        let partial_lt: syn::Lifetime = syn::parse_quote!('scylla_ser_partial);
`LifetimeParam` is something like: `'a: 'b + 'c`, whereas `Lifetime` is just: `'a` or `'b`. The reason for this change is that I want to add `'scylla_ser_partial` as a bound to every lifetime parameter currently existing in the partial struct. To do that, I need to add just the "lifetime" named `'scylla_ser_partial` to the existing bounds. 

Put it another way, the types that `syn` has for bounds to lifetime parameters are lifetimes, not lifetime parameters: https://docs.rs/syn/latest/syn/struct.LifetimeParam.html

2025-03-16 21:21 UTC, nrxus commented
> This looks really useful, but wondering if the flatten attribute can also be added to derive SerializeValue, which I'm using for a bunch of UDTs I have in my app?
> 
> I have a struct that's used independently in some parts of my code, which I include in my main struct that essentially derives SerializeValue in order to implement a UDT.

After this is merged I may take a look at it whenever I have time but since I don't use UDTs and this PR is already pretty large I would be hesitant to adding more features as part of this PR.

2025-03-16 21:23 UTC, nrxus commented
> 🚀 🎉 🦀 This is one of the highest quality external contributions I've ever reviewed! Great job!

Thank you for the compliment and the review! (:

I have addressed all the simple comments but there are a couple of remaining questions, let me know when those are decided and I'll make any necessary changes.

2025-03-16 23:14 UTC, Lorak-mmk commented on scylla-cql/src/lib.rs
> +    }
I did not read the code at all yet, but one thing caught my eye when I glanced at it: this adds a lot of code in lib.rs - and its a real code, not just re-exports. Could you extract it to a separate file? I'd like to minimize amount of non-trivial code in mod.rs / lib.rs if possible.

2025-03-17 06:38 UTC, wprzytula commented on scylla-macros/src/serialize/row.rs
> +        };
> If the concern is the slow hash during look-up

Indeed, this is my concern. OK, I assume we could use a faster hash. But wouldn't a `Vec`-based offline set be still faster for this case?

2025-03-17 06:40 UTC, wprzytula commented on scylla-macros/src/serialize/row.rs
> +        let partial_lt: syn::Lifetime = syn::parse_quote!('scylla_ser_partial);
:+1:, please put the above explanation in the commit message.

2025-03-17 07:50 UTC, wprzytula reviewed
The general request before continuing with the review: please restructure commits as I've described in multiple comments now.

2025-03-17 07:50 UTC, wprzytula commented on scylla-cql/src/lib.rs
> +            ) -> Result<WrittenCellProof<'b>, SerializationError> {
> FWIW this function is basically just extracting code that was manually written inside the macro code (and hence added to code bloat anyway but at macro expansion time).

:recycle: In such case, could you make extraction of that function a separate preparatory commit that comes before the commits that bring the _flatten_ functionality?
I mean, if I understand the structure of your changes correctly, they could be divided into the refactor part (introducing the new `SerializeRowByName` etc. abstractions) and the new functionality part (adding logic to support `#[flatten]`). I believe such separation will make the review easier.

2025-03-17 07:50 UTC, wprzytula commented on scylla-cql/src/lib.rs
> +            ) -> Result<WrittenCellProof<'b>, SerializationError> {
If it's possible, I'd like to have refactors always first and new features second in a PR. This way we can first make sure that the driver is still in a valid state wrt existing logic, and then we can discuss the new logic serving the new features.

With that said, I'd prefer to have the `_macro_internal` module extraction come before all further refactors that are touching that module. That's also important for further readers to have the `git blame` highlight the proper commit which adds the functionality/logic instead of the commit that merely extracts the module.

2025-03-17 07:50 UTC, wprzytula commented on scylla-cql/src/serialize/row_tests.rs
> +    }
:wrench: Just to make sure, let's also have a test case with `skip_name_checks` set.

2025-03-17 07:50 UTC, wprzytula commented on scylla-cql/src/serialize/row_tests.rs
> +    }
:seedling: When considering adding `#[flatten]` support for `(De)SerializeValue`, too, we'll need to consider how `flatten` interacts with `allow_missing` and `default_when_null`.

2025-03-17 07:50 UTC, wprzytula commented on scylla-cql/src/lib.rs
> +            ) -> Result<WrittenCellProof<'b>, SerializationError> {
> Some of the declarative macros also could probably be simplified by using this function.

Let's do that! (in a separate commit coming before the new features, as mentioned)

2025-03-17 07:50 UTC, wprzytula commented on scylla-macros/src/serialize/row.rs
> +    // flattned as if they were in the parent struct.
:pick:

2025-03-17 07:50 UTC, wprzytula commented on scylla-macros/src/serialize/row.rs
> +    // flattned as if they were in the parent struct.
```suggestion
    // If set, then the field is inlined into the struct, that is, it is serialized using `SerializeRow`,
    // with the serialized fields flattened into (possibly multiple) columns as if they were
    // in the parent struct.
```

2025-03-17 17:18 UTC, rc-andres commented on scylla-cql/src/lib.rs
> +            ) -> Result<WrittenCellProof<'b>, SerializationError> {
The introduction of the new traits and structs are only there for the purpose of the flatten feature, without it, those traits don't do anything (as they are doc hidden). But I will try do the rest of the commit/file surgery (:

2025-03-17 17:21 UTC, wprzytula commented on scylla-cql/src/lib.rs
> +            ) -> Result<WrittenCellProof<'b>, SerializationError> {
I understand their purpose is to support `flatten`; but IIUC, now they also serve the non-`flatten` use cases. Correct?
If so, then let's first refactor the code to use the new abstractions without `flatten` support yet, and then let's extend it with `flatten` functionalities.

2025-03-17 18:17 UTC, rc-andres commented on scylla-cql/src/lib.rs
> +                    value: &impl SerializeValue,
Added inline as you recommended for the other function.

2025-03-17 18:26 UTC, rc-andres commented on scylla-cql/src/serialize/row.rs
>  }
Fwiw I first tried something similar to this but a compilation error was raised. If an item is `pub(crate)` then it is not allowed for another module to re-export it as far as I could tell (but maybe it works different if the item is public and the module is `pub(crate)` as you said, I am not sure). 

Either way I think that by default rust analyzer doesn't grab doc hidden items thus using it by accident would be unlikely. Also, by virtue of it being `doc(hidden)` there are no semver guarantees so I don't think it is needed to do much more.

2025-03-17 18:43 UTC, Lorak-mmk commented on scylla-cql/src/serialize/row_tests.rs
> +    }
I'd like that to be discussed before we merge this PR. I'd like to avoid a situation where we merge this, release it, and then it turns out there is some fundamental issue with adding flatten to other traits.

2025-03-17 18:47 UTC, nrxus commented on scylla-macros/src/serialize/row.rs
> +        };
I don't quite get how we would index into the `Vec<(&str, bool)>`. We would need to convert the key into a number to index which is the same problem, how do we go from key name to a number.

2025-03-17 19:01 UTC, nrxus commented on scylla-cql/src/serialize/row_tests.rs
> +    }
I am going to assume you mean `DeserializeValue` and `DeserializeRow` as I don't see anything in `SerializeValue`'s attributes that would conflict. 

Maybe I am missing something obvious, but I think it'd be the same as I added for the `rename` attribute, namely you cannot say to flatten a field and have those attributes on the same field because they don't make sense together. 

There are three attributes that allow defaulting:

* `skip`: It doesn't make sense to say "flatten the inner fields from this field but also skip it". So at compile time we would disallow it. 
* `allow_missing`: It doesn't make sense to allow the field-to-be-flattened to be missing because that field doesn't exist, only its inner fields (may) exist. So at compile time we would disallow it. 
* `default_when_null`: Similar to above, the field is never "null" and never "not null", it just doesn't exist, only its inner fields exist. So at compile time we would disallow it. 

As for how we'd deal if the inner fields have those attributes, I think it is the same as if the outer attributes have those attributes: when deserializing and creating the instance we'll probably have some sort of partial struct that is aware of what fields are required and what is not, so at the end we'd go through each field and try to "finish it" which would check if they have gotten all the required fields, default the rest, and return a fully realized instance of the struct.

2025-03-17 20:45 UTC, rc-andres commented on scylla-cql/src/lib.rs
> +            ) -> Result<WrittenCellProof<'b>, SerializationError> {
Ah okay, I understand now. I can do that, it will take a little bit of commit surgery but it hopefully isn't too bad.

2025-03-17 20:53 UTC, nrxus commented on scylla-cql/src/serialize/row.rs
>  }
based on the [discussion here](https://github.com/rust-lang/rust-analyzer/issues/7718) (and my own experience), rust analyzer does not suggest hidden items, but it does suggest doc hidden re-exports. Since we are doc hiding the actual function here, not doc hiding a re-export then it shouldn't be caught by rust-analyzer. And in fact, when I tried just now inside the `scylla` crate, if I type `mk_ser` I don't any suggestions for `mk_ser_err`. 

I am happy to do whatever you all think is right though, I don't have a strong opinion here on how to not add this function to the public API while still letting macros use it.

2025-03-17 23:54 UTC, nrxus commented on scylla-cql/src/lib.rs
> +            ) -> Result<WrittenCellProof<'b>, SerializationError> {
Done, I did it in two separate commits: one to refactor for deriving when serializing by name and one for deriving when serializing with order enforced.

2025-03-25 20:41 UTC, nrxus commented
@wprzytula are there any other changes necessary for this PR?

2025-03-26 08:55 UTC, wprzytula commented
> @wprzytula are there any other changes necessary for this PR?

Sorry for the delay, I've had a large number of reviews recently. I'm going to review it today or tomorrow.

2025-03-27 13:08 UTC, wprzytula commented on scylla-cql/src/_macro_internal.rs
> +            ) -> Result<WrittenCellProof<'b>, SerializationError> {
:wrench: `next` is commonly associated with `Iterator`, as a method that simply returns consecutive items.

2025-03-27 13:08 UTC, wprzytula commented on scylla-cql/src/_macro_internal.rs
> +            ) -> Result<WrittenCellProof<'b>, SerializationError> {
```suggestion
            pub fn serialize_next_column<'b, T, const ENFORCE_NAME: bool>(
                &mut self,
                expected: &str,
                value: &impl SerializeValue,
                writer: &'b mut RowWriter<'_>,
            ) -> Result<WrittenCellProof<'b>, SerializationError> {
```

2025-03-27 13:09 UTC, wprzytula commented on scylla-cql/src/_macro_internal.rs
> +            #[inline]
After another though, let's be explicit. `SerializerByColumnOrder`?
And the other would be `SerializerByColumnName`.

2025-03-27 21:33 UTC, nrxus commented on scylla-cql/src/serialize/row.rs
> +                    $crate::_macro_internal::ser::row::serialize_column::<Self>($fidents, $tidents, writer)?;
The error message isn't changed here. The error message (if you see L290 on the old code) was ``Self` and it continues to be from `Self`. The old `$typs` here was not for the error message but to fully qualify the ``serialize` method for the type of `$fidents`. We no longer need to do that fully qualified syntax because we are no longer calling a trait method but instead just a standalone function that takes `$fidents` as a generic parameter.

2025-03-27 21:34 UTC, nrxus commented on scylla-macros/src/serialize/row.rs
> +                            #crate_path::ser::row::serialize_column::<Self>(&self.#rust_field_idents, spec, writer)?;
Same as my answer above.

2025-03-27 21:49 UTC, nrxus commented on scylla-macros/src/serialize/row.rs
> +        let fields: Vec<_> = self.ctx.fields.iter().map(|f| &f.ident).collect();
Yep, that's exactly right.

2025-03-27 22:32 UTC, nrxus commented on scylla-macros/src/serialize/row.rs
> +                }
I have added some more comments on this commit and the commit that actually implements flattening for serializing by name. Let me know if this helps clarify it some.

2025-03-27 22:36 UTC, nrxus commented on scylla-cql/src/_macro_internal.rs
> +            #[inline]
I am okay changing the names but just to explain my rationale for their current short names to see if it's persuasive: I explicitly put these structs inside the inner module: `ser::row`. So in my head this structs are `ser::row::ByColumn`  and `ser::row::ByName` so it is already clear that I am serializing row by name and serializing row by column. 

In traits, however, I do tend to name them fully because traits need to be imported for methods on them to be called whereas structs we can just qualify them if we are outside of the "serialize row" context.

2025-03-27 22:51 UTC, nrxus commented on scylla-cql/src/_macro_internal.rs
> +            #[inline]
I renamed this struct since this one is a little different in that it is a "serializer" while the other ones are just wrappers around the serializable data.

2025-03-27 22:58 UTC, nrxus commented on scylla-cql/src/_macro_internal.rs
> +            ) -> Result<WrittenCellProof<'b>, SerializationError> {
I renamed the struct to be `NextColumnSerializer` and this function to `serialize` which I think already implies "next" given the name of the struct. Let me know if you think that is enough.

2025-03-27 22:58 UTC, nrxus commented on scylla-cql/src/_macro_internal.rs
> +        impl<T: SerializeRowInOrder> InOrder<'_, T> {
I added docs, but read my reply above on why the name is terse. But I am OK changing it if you still think it's too terse even within the context of the module.

2025-03-31 21:15 UTC, nrxus commented on scylla-cql/src/_macro_internal.rs
> +                match self.columns.next() {
You are totally right, I have no idea why I didn't do that to begin with 🤦🏾

2025-04-02 12:31 UTC, wprzytula commented on scylla-cql/src/_macro_internal.rs
> +            ) -> Result<WrittenCellProof<'b>, SerializationError> {
It's OK for me.

2025-04-02 12:34 UTC, wprzytula approved these changes
Once again, thanks a lot! :sparkles:

2025-04-04 16:17 UTC, nrxus commented
@wprzytula is there anything needed for merging?

2025-04-06 14:50 UTC, Lorak-mmk commented
> @wprzytula is there anything needed for merging?

I'd like to also review this. I'll try to get to it shortly.

2025-04-07 11:56 UTC, Lorak-mmk requested changes
Looks quite good! Thank you for this contribution.

The only bigger change I'd like to see is getting rid of the HashSet.
Before we used local vars for flags and counter. Those should be easily convertible to partial struct fields.
Unless there is some good reason for this change we should stick to flags and counters instead of hashset.
If there is a good reason it should be included in the commit message,


> The error produced if these two flavors are matched will be at compile time but it may not be the clearest error since it would be about the struct not implementing some doc hidden trait they wouldn't be able to see in the docs.

You can use https://doc.rust-lang.org/reference/attributes/diagnostics.html#the-diagnosticon_unimplemented-attribute to make the error message better. It requires Rust 1.78 I think, but we can bump our MSRV to this version. In fact in the other unmerged PR I bump it to 1.80, you can cherry pick the relevant commits from there: https://github.com/scylladb/scylla-rust-driver/pull/1296

> I have only added this attribute to SerializeRow because it was easier than DeserializeRow but I also want to add it to that macro in a future PR next chance I get to dig into this code.

Great! We should add it to value ser/deser too in the future, not only row.

> Maybe in the future those could be made public but it felt too early to know if all the signatures were exactly how we wanted to expose them or not.

I don't see a good reason to make them public, now or in the future.

> For context, I am currently dealing with an issue that if I have different insert queries where one sets N columns and another one sets the same N and one extra, then I have two make two structs with N repeated fields. With this PR I'd be able to to instead flatten the struct with N fields inside the other struct to make my code more maintainable.

That's a very reasonable use case for that feature. I did not yet read the changes, so it may already be done, but this is something that should definitely be put as an example in the docs (and maybe in the examples/ folder too).

2025-04-07 11:56 UTC, Lorak-mmk commented on scylla-cql/src/_macro_internal.rs
> +}
❓ I'd just like to check if I understand this well:
check_missing will return `Ok` if either:
- some previous call to `serialize_field` returned `Ok(Done)`
- struct is empty

Otherwise it will return an error.

If that is not correct, please describe relation between the methods a bit more so that the reader can build some intuition.
If it is correct, the reasons for `check_missing` are:
- Empty structs
- Generating error messages
because those cases are the only things not covered by remembering if `Ok(Done)` wes returned before.
Am I right, or do I misunderstand the purpose of this?

2025-04-07 11:56 UTC, Lorak-mmk commented on scylla-cql/src/_macro_internal.rs
> +        }
Ok here is where my question above starts to matter. Are there other reasons besides empty structs why we call `check_missing` instead of remembering of `Done` was returned after the last column?

2025-04-07 11:56 UTC, Lorak-mmk commented on scylla-cql/src/serialize/row.rs
>  }
Let's leave it as-is for now.

2025-04-07 11:56 UTC, Lorak-mmk commented on scylla-macros/src/serialize/row.rs
> +        } else {
When I said to not worry about the hashset I was not aware that it would also be necessary for the case where `flatten` is not used. This introduces new overhead to the case that does not need it.

Before we used local variables (one per field) to track completion. The obvious way to migrate that to partial struct would be to have bool fields in the struct, instead of local variables. Why do we need a set instead of that?

2025-04-07 11:56 UTC, Lorak-mmk commented on scylla-macros/src/serialize/row.rs
Nit: Why use `tys`?
For a singular we can't use `type` because it is reserved in Rust (which is imo a mistake). We usually use `typ`, not sure why `ty` is used here.
For plural I see no reason to use `tys` instead of `types`.

2025-04-07 18:38 UTC, nrxus commented on scylla-macros/src/serialize/row.rs
> +        } else {
When I first wrote this it got into my head that I *really* needed the hashset because I couldn't keep track of the flattened fields at compile time but I think that may have been the case for a previous implementation that ended up not going anywhere. I think the current implementation could probably just be done with one boolean per field in the struct, I'll give it a shot.

2025-04-07 18:51 UTC, nrxus commented on scylla-macros/src/serialize/row.rs
> +                writer: &mut #crate_path::RowWriter<'_scylla_ser_row_writer_buffer>,
Probably doable but I am unsure if the effort is worth it. From my understanding it is common practice in macros to use underscores when wanting to specify a lifetime that is more guaranteed to not clash.

2025-04-07 18:54 UTC, Lorak-mmk commented on scylla-macros/src/serialize/row.rs
Yeah let's do that. It will be more consistent with the rest of this project.

2025-04-07 19:03 UTC, nrxus commented on scylla-macros/src/serialize/row.rs
There are untouched spots right now where `ty` is used instead of `typ`. Would you want me to address those too?

2025-04-07 19:05 UTC, Lorak-mmk commented on scylla-macros/src/serialize/row.rs
You can if you have time, but it is of course not required to merge this PR.

2025-04-07 21:34 UTC, nrxus commented on scylla-macros/src/serialize/row.rs
I did it for the easy ones but in `DeserializeRow` and `DeserializeValue`  they need to stay as `ty` since the `darling` crate depends on those names.

2025-04-07 21:36 UTC, nrxus commented on scylla-macros/src/serialize/row.rs
> +        } else {
Done. I have it now the same way as it used to be: a counter that keeps track of how many fields are remaining to serialize, and a per-field boolean to check what fields have already been visited.

2025-04-08 12:25 UTC, wprzytula approved these changes

2025-04-08 12:25 UTC, wprzytula commented on scylla-macros/src/serialize/row.rs
> +                            self.remaining_count -=1;
:pick:

2025-04-08 12:25 UTC, wprzytula commented on scylla-macros/src/serialize/row.rs
> +                            self.remaining_count -=1;
```suggestion
                            self.remaining_count -= 1;
```

2025-04-08 16:22 UTC, Lorak-mmk commented on scylla-cql/src/_macro_internal.rs
> +}
Ok, thanks!

2025-04-08 16:35 UTC, nrxus commented on scylla-cql/src/_macro_internal.rs
> +        }
Sorry, I phrased it weird. I should have said:

The first call to check_missing **could be made** only if we didn't detect a Done, but that call to check_missing may call to flattened struct's check_missing if the field that it detected was incomplete was a flattened struct.

So yes, we can have an `if` check to only call it if we didn't detect a `Done`. But as I said in another comment, the happy case for that function is very cheap (just an `if num_remaining == 0`) so we'd be trading an if for another 🤷🏾

2025-04-08 16:49 UTC, nrxus commented
I know this PR is pretty big so I really appreciate the time and effort you are all taking in reviewing this and giving me some great feedback (:

2025-04-08 18:02 UTC, Lorak-mmk commented on scylla-cql/src/_macro_internal.rs
> +
`serialize` here should be `#[inline]`.

2025-04-08 18:18 UTC, muzarski commented on scylla-cql/src/_macro_internal.rs
> +                }
> Commit: refactor deriving SerializeRow when serializing by name
> 
> I see that in the by-name variant the errors are used correctly. If some column of the statement was not used we return `NoColumnWithName` and if some rust fields are not used after all statement columns are serialized we return `ValueMissingForColumn`

Fun fact: I stumbled upon this issue when I played around and tried to implement https://github.com/scylladb/scylla-rust-driver/pull/1315. But I didn't investigate further - assumed that this is due to my poor usage of macros...

2025-04-08 18:22 UTC, muzarski commented on scylla-cql/src/_macro_internal.rs
> +
> Soooo I think we have a pre-existing bug, and those errors usage should be switched around here. cc @piodul and @wprzytula because maybe I am not understanding something here

I agree that this is not right. As I mentioned in my other comment, I stumbled upon this before and was really confused.

2025-04-08 18:59 UTC, nrxus commented on scylla-macros/src/serialize/row.rs
> +                #crate_path::ser::row::ByName(self).serialize(ctx, writer)
The purpose of `SerializeRowByName` is to have a trait that enforces the requirement of a `partial()` method and keeps track of the type of the returned partial struct (in the form of the associated type). 

 Inside this function we could probably just manually construct the partial struct manually but we also need to create the partial struct inside `SerializeRowByName::partial` for any field that is being flattened. And when declaring the partial struct for the parent struct, we need to specify the type of any flattened field's partial struct, and we can do that by doing: `<#flattened_types as #crate_path::SerializeRowByName>::Partial<#partial_lt>,)`

I did just notice that the call to `partial()` inside `SerializeRowByName::partial` isn't fully qualified, I wonder if it needs to be. I thought that calling methods on traits required the trait to be imported but we never import it and yet it works though so maybe there is more going on there so it's fine as is I am not sure.

2025-04-08 19:06 UTC, Lorak-mmk commented on scylla-macros/src/serialize/row.rs
> +                #crate_path::ser::row::ByName(self).serialize(ctx, writer)
Ok that explanation convinced me, thanks.

Any code generated by macro should be fully qualified. You just made me realized that I forgot to check that during the review...

2025-04-08 19:11 UTC, nrxus commented
> Oh, actually one more thing: in the previous review I proposed using https://doc.rust-lang.org/reference/attributes/diagnostics.html#the-diagnosticon_unimplemented-attribute to improving error message when the user tries to use `#[flatten]` on a field that does not support it. I think you may have missed that because I posted that in the review summary, instead of a separate comment.

Ah, that's cool, I've never used that before. Do you have any ideas for a good error message? 

For context, the current error for having an outer by-name serialization and an inner in-order serialization looks like:

```bash
error[E0277]: the trait bound `serialize::row::tests::foobar::Inner: SerializeRowByName` is not satisfied
    --> scylla-cql/src/serialize/row_tests.rs:1220:14
     |
1220 |     #[derive(SerializeRow)]
     |              ^^^^^^^^^^^^ the trait `SerializeRowByName` is not implemented for `serialize::row::tests::foobar::Inner`
     |
     = help: the following other types implement trait `SerializeRowByName`:
               &T
               RowWithTTL
               TestRowWithColumnRename
               TestRowWithColumnSorting
               TestRowWithGenerics<'a, T>
               TestRowWithNoColumns
               TestRowWithSkippedFields
               serialize::row::tests::foobar::Outer
             and 3 others
     = note: this error originates in the derive macro `SerializeRow` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0599]: no method named `partial` found for struct `serialize::row::tests::foobar::Inner` in the current scope
    --> scylla-cql/src/serialize/row_tests.rs:1220:14
     |
1216 |     struct Inner {
     |     ------------ method `partial` not found for this struct
...
1220 |     #[derive(SerializeRow)]
     |              ^^^^^^^^^^^^ method not found in `Inner`
     |
     = help: items from traits can only be used if the trait is implemented and in scope
note: `SerializeRowByName` defines an item `partial`, perhaps you need to implement it
    --> scylla-cql/src/_macro_internal.rs:41:1
     |
41   | pub trait SerializeRowByName {
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     = note: this error originates in the derive macro `SerializeRow` (in Nightly builds, run with -Z macro-backtrace for more info)

Some errors have detailed explanations: E0277, E0599.
For more information about an error, try `rustc --explain E0277`.
error: could not compile `scylla-cql` (lib test) due to 5 previous errors
```

The inverse case looks like:

```bash
error[E0277]: the trait bound `serialize::row::tests::foobar::Inner: SerializeRowInOrder` is not satisfied
    --> scylla-cql/src/serialize/row_tests.rs:1220:14
     |
1220 |     #[derive(SerializeRow)]
     |              ^^^^^^^^^^^^ the trait `SerializeRowInOrder` is not implemented for `serialize::row::tests::foobar::Inner`
     |
     = help: the following other types implement trait `SerializeRowInOrder`:
               &T
               TestRowWithColumnRenameAndEnforceOrder
               TestRowWithEnforcedOrder
               TestRowWithSkippedNameChecks
               serialize::row::tests::foobar::Outer
               serialize::row::tests::test_flatten_row_serialization_with_enforced_order_and_skip_namecheck::InnerColumnsOne
               serialize::row::tests::test_flatten_row_serialization_with_enforced_order_and_skip_namecheck::InnerColumnsTwo
               serialize::row::tests::test_flatten_row_serialization_with_enforced_order_and_skip_namecheck::OuterColumns
             and 6 others
     = note: this error originates in the derive macro `SerializeRow` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0277`.
error: could not compile `scylla-cql` (lib test) due to 1 previous error
```

2025-04-08 19:56 UTC, nrxus commented on scylla-cql/src/_macro_internal.rs
> +                }
I didn't actually fix anything, in the new code when serializing by name it still returns `ValueMissingForColumn` when there are unserialized rust fields but (if I understood correctly) you are saying that `ValueMissingForColumn` should be returned when where there is a column spec that is missing a rust field.

2025-04-08 20:21 UTC, Lorak-mmk commented on scylla-cql/src/_macro_internal.rs
> +                }
Yeah sorry, I misunderstood your code. It looks like the bug is present both before and after, for both variants.

2025-04-08 21:09 UTC, Lorak-mmk commented
> Ah, that's cool, I've never used that before. Do you have any ideas for a good error message?
> 
> For context, the current error for having an outer by-name serialization and an inner in-order serialization looks like:

I took a stab at writing those messages, but I see you were faster.  My commits are available at: https://github.com/Lorak-mmk/scylla-rust-driver/tree/flatten-serialize-name
I'm not sure which messages are better, mine or yours. I'll let you and others (cc @wprzytula @muzarski ) decide.

Here's my proposed error message for the first case (match_by_name). 
The second error probably exists only because the call is not fully qualified, right? Let's definitely get rid of unqualified calls.

```rust
cargo check
    Blocking waiting for file lock on build directory

    Checking scylla-cql v1.1.0 (/home/karolbaryla/repos/scylla-rust-driver/scylla-cql)
error[E0277]: `InnerStruct` cannot be flattened here
  --> scylla-cql/src/lib.rs:27:10
   |
27 | #[derive(SerializeRow)]
   |          ^^^^^^^^^^^^ `InnerStruct` is not a struct that derives `SerializeRow` with `match_by_name` flavor
   |
   = help: the trait `SerializeRowByName` is not implemented for `InnerStruct`
   = note: There are two common reasons for that:
           - `InnerStruct` does not use `#[derive(SerializeRow)]`
           - `InnerStruct` uses `#[scylla(flavor = "enforce_order")]`
   = help: the trait `SerializeRowByName` is implemented for `OuterStruct`
   = note: this error originates in the derive macro `SerializeRow` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0599]: no method named `partial` found for struct `InnerStruct` in the current scope
  --> scylla-cql/src/lib.rs:27:10
   |
23 | struct InnerStruct {
   | ------------------ method `partial` not found for this struct
...
27 | #[derive(SerializeRow)]
   |          ^^^^^^^^^^^^ method not found in `InnerStruct`
   |
   = help: items from traits can only be used if the trait is implemented and in scope
note: `SerializeRowByName` defines an item `partial`, perhaps you need to implement it
  --> scylla-cql/src/_macro_internal.rs:48:1
   |
48 | pub trait SerializeRowByName {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   = note: this error originates in the derive macro `SerializeRow` (in Nightly builds, run with -Z macro-backtrace for more info)

Some errors have detailed explanations: E0277, E0599.
For more information about an error, try `rustc --explain E0277`.
error: could not compile `scylla-cql` (lib) due to 5 previous errors
```

And here's the message for enforce_order case.

```rust
cargo check
    Checking scylla-cql v1.1.0 (/home/karolbaryla/repos/scylla-rust-driver/scylla-cql)
error[E0277]: `InnerStruct` cannot be flattened here
  --> scylla-cql/src/lib.rs:35:10
   |
35 | #[derive(SerializeRow)]
   |          ^^^^^^^^^^^^ `InnerStruct` is not a struct that derives `SerializeRow` with `enforce_order` flavor
   |
   = help: the trait `SerializeRowInOrder` is not implemented for `InnerStruct`
   = note: There are two common reasons for that:
           - `InnerStruct` does not use `#[derive(SerializeRow)]`
           - `InnerStruct` uses `#[scylla(flavor = "match_by_name")]` (which is the default)
   = help: the trait `SerializeRowInOrder` is implemented for `OuterStructOrdered`
   = note: this error originates in the derive macro `SerializeRow` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0277`.
error: could not compile `scylla-cql` (lib) due to 1 previous error
```

2025-04-08 21:25 UTC, nrxus commented
> I took a stab at writing those messages, but I see you were faster. My commits are available at: https://github.com/Lorak-mmk/scylla-rust-driver/tree/flatten-serialize-name I'm not sure which messages are better, mine or yours. I'll let you and others (cc @wprzytula @muzarski ) decide.

I am perfectly happy with your version so I just did that and indeed once I switched to fully qualifying the path then there is only one error for the first case as expected:

```bash
error[E0277]: `serialize::row::tests::foobar::Inner` cannot be flattened here
    --> scylla-cql/src/serialize/row_tests.rs:1220:14
     |
1220 |     #[derive(SerializeRow)]
     |              ^^^^^^^^^^^^ `serialize::row::tests::foobar::Inner` is not a struct that derives `SerializeRow` with `match_by_name` flavor
     |
     = help: the trait `SerializeRowByName` is not implemented for `serialize::row::tests::foobar::Inner`
     = note: There are two common reasons for that:
             - `serialize::row::tests::foobar::Inner` does not use `#[derive(SerializeRow)]`
             - `serialize::row::tests::foobar::Inner` uses `#[scylla(flavor = "enforce_order")]`
     = help: the following other types implement trait `SerializeRowByName`:
               RowWithTTL
               TestRowWithColumnRename
               TestRowWithColumnSorting
               TestRowWithGenerics<'a, T>
               TestRowWithNoColumns
               TestRowWithSkippedFields
               serialize::row::tests::foobar::Outer
               serialize::row::tests::test_row_serialization_nested_structs::InnerColumnsOne
             and 2 others
     = note: this error originates in the derive macro `SerializeRow` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0277`.
error: could not compile `scylla-cql` (lib test) due to 4 previous errors

```

2025-04-09 07:22 UTC, wprzytula commented on scylla-cql/src/_macro_internal.rs
> +
Agreed. It's even more funny: when I wrote deserialization errors & macros based on existing serialization code, I was confused about those errors, too, but did not connect the dots that there is a bug in serialization.

2025-04-09 07:30 UTC, wprzytula submitted a review, later dismissed

2025-04-09 09:36 UTC, Lorak-mmk requested changes
Last 2 minor changes.

2025-04-09 09:36 UTC, Lorak-mmk commented on scylla-macros/src/serialize/row.rs
> +                                // there is a column and the field is done
Ugh, I reall thought I would give approve this time, but there is one more unqualified call :(

2025-04-09 09:36 UTC, Lorak-mmk commented on scylla-macros/src/serialize/row.rs
> +
And another one here

2025-04-09 09:57 UTC, Lorak-mmk commented
I see at least one other unqualified call. Give me a moment, I'll fix them and push to your branch.

2025-04-09 10:35 UTC, Lorak-mmk commented
I've pushed some changes to my branch ( https://github.com/Lorak-mmk/scylla-rust-driver/tree/flatten-serialize-name ), feel free to use it.
- Got rid of unqualified calls
- Moved one formatting change to a different commit. Without that `make static` is not passing on one commit.

I have no more issues with this version, so if you decide to use it I can approve without another review.

2025-04-09 16:33 UTC, nrxus commented
I am not quite sure how to diff your changes against mine so I can pick your changes (since they were just rebased) so I am going to fix the few spots you mentioned manually.

2025-04-09 16:36 UTC, nrxus commented
I have rebased my branch against yours such that this PR now has your changes. Let me know if that's enough.

2025-04-09 16:46 UTC, Lorak-mmk approved these changes
Really great work! I hope you don't hate us too much for that many review rounds 😅
I don't think we need to wait for @wprzytula - he approved it many times already.

2025-04-09 16:46 UTC, merged

2025-04-09 18:40 UTC, nrxus commented
Thanks for the approval and merge! No worries about the many rounds, it was a big change so I appreciate thoroughness!