Proceed on unresolvable hostname
scylladb/scylla-rust-driver pull request #753
Opened 2023-07-01 09:42 UTC by wprzytula

A user encountered a following problem:
> Rust Driver wasn't able to start if one of the configured nodes was not available

This was found to be caused by the hostname resolution logic, which considered failure in resolving any hostname to be a critical error.
As it makes more sense to fail only when we end up with no contact points with known resolved addresses, in that case, a new variant is returned: `NewSessionError::FailedToResolveAnyHostname`, else initialisation continues successfully.
The new behaviour is automatically tested.

## Pre-review checklist

- [x] I have split my patch into logically separate commits.
- [x] All commit messages clearly explain what they change and why.
- [x] I added relevant tests for new features and bug fixes.
- [ ] All commits compile, pass static checks and pass test.
- [x] PR description sums up the changes and reasons why they should be introduced.
- [x] I have provided docstrings for the public items that I want to introduce.~~
- ~~[ ] I have adjusted the documentation in `./docs/source/`.~~
- ~~[ ] I added appropriate `Fixes:` annotations to PR description.~~

2023-07-02 06:18 UTC, mykaul commented
0.8.x material?

2023-07-03 05:07 UTC, wprzytula commented
> 0.8.x material?

This unfortunately contains an API-breaking change, so we can release it only with a new major number, i.e. 0.9.x.
WDYT @piodul ?

2023-07-04 10:53 UTC, piodul requested changes

2023-07-05 08:51 UTC, wprzytula commented on scylla/src/transport/session.rs
> +                }
I believe `Result` conveys the intention better. After all, `Err` points at some kind of failure, while `None` can as well signify a correct situation. I would stick to `Result`.

2023-07-05 12:42 UTC, piodul commented on scylla/src/transport/session.rs
> +                }
Not sure if I agree. We are ignoring the errors, after all - we are ignoring the hostnames for which resolution failed and using only the successful ones. `filter_map` + returning `Option` is a common pattern which I think is pretty clear. Returning `Result` here only suggests that you are going to do something useful with the error later.

2023-07-06 09:54 UTC, wprzytula commented on scylla/src/transport/session.rs
> +                }
I'm convinced now. Adjusted this.

2023-07-06 12:32 UTC, piodul commented on scylla/tests/integration/new_session.rs
> +    let uri = "cassandrasuckssomu.ch:9042".to_owned();
This one is not fixed yet.

2023-07-06 13:37 UTC, piodul approved these changes

2023-07-06 13:37 UTC, merged