default policy: Rack awareness without token awareness
scylladb/scylla-rust-driver pull request #777
Opened 2023-07-30 18:43 UTC by wprzytula

Until now, the default policy respected rack preference only when it came to replicas.
Considering non-token-aware queries (e.g. unprepared statements), they would never prioritize the preferred rack.

Now, local rack nodes are always preferred before other nodes, both in `pick()` and in `fallback()`.

The PR contains breaking changes, as it slightly changes signature of `ReplicaSet::choose_filtered()` (note the reference added).

Tests are TODO.

## Pre-review checklist

- [x] I have split my patch into logically separate commits.
- [x] All commit messages clearly explain what they change and why.
- [ ] I added relevant tests for new features and bug fixes.
- [x] All commits compile, pass static checks and pass test.
- [x] PR description sums up the changes and reasons why they should be introduced.
- ~~[ ] I have provided docstrings for the public items that I want to introduce.~~
- [ ] I have adjusted the documentation in `./docs/source/`.
- ~~[ ] I added appropriate `Fixes:` annotations to PR description.~~

2023-07-31 08:43 UTC, piodul approved these changes
LGTM

@havaker please take a look as well

2023-07-31 08:43 UTC, piodul commented on scylla/src/transport/load_balancing/default.rs
> +
The `token_with_strategy.is_some()` and `token_with_strategy_is_none()` paths look very similar. Perhaps we could unify them somehow? Not necessarily here, just food for thought for future improvements.

2023-08-01 13:53 UTC, havaker requested changes

2023-08-01 13:53 UTC, havaker commented on scylla/src/transport/load_balancing/default.rs
> +                    .group([A]) // local rack nodes
> Considering non-token-aware queries (e.g. unprepared statements), they would never prioritize the preferred rack.

I'd like to see a test which has `routing_info` with a `token` field set to `None`.

2023-08-01 13:53 UTC, havaker commented on docs/source/load-balancing/default-policy.md
> +When a preferred rack is set, the policy will first return nodes in the local rack
kudos for updating the documentation!

2023-08-02 07:53 UTC, wprzytula commented
v2:
- renamed `ReplicaLocation[Criteria|Location]` to `Node...`
- provided a test for rack awareness when no token is known
- rebased on `main`

2023-08-02 08:14 UTC, havaker approved these changes

2023-08-03 17:24 UTC, piodul approved these changes

2023-08-03 17:25 UTC, merged