Prepare query
scylladb/scylla-rust-driver pull request #806
Opened 2023-09-01 08:53 UTC by sylwiaszunejko

## Motivation
See the referenced issue (#800)

## What's done
Information about the types of the bind markers is necessary to make the serialization API safe (i.e. so that the user data won't be misinterpreted when sending it to the database). The problem with unprepared statements is that the driver doesn't have a good way to determine column names and types of the bind markers.

Now before sending an unprepared statement, it is quietly prepared on one connection to obtain the information about the bind markers. If the list of values to be bound is empty, we just send it as an unprepared query.

## Evaluation
Integration tests are added.

Fixes: #800 

## Pre-review checklist

- [x] I have split my patch into logically separate commits.
- [x] All commit messages clearly explain what they change and why.
- [x] I added relevant tests for new features and bug fixes.
- [x] All commits compile, pass static checks and pass test.
- [x] PR description sums up the changes and reasons why they should be introduced.
- [ ] I have provided docstrings for the public items that I want to introduce.
- [ ] I have adjusted the documentation in `./docs/source/`.
- [x] I added appropriate `Fixes:` annotations to PR description.

2023-09-01 09:58 UTC, piodul requested changes

2023-09-01 09:58 UTC, piodul commented on scylla/src/transport/session.rs
> +                    let values_size = values.serialized().unwrap().into_owned().size();
`.serialized()` is an operation that can be potentially costly. It is already computed on line 624, so I suggest using the already computed `serialized_values` instead.

2023-09-01 09:58 UTC, piodul commented on scylla/src/transport/session.rs
> +                                .unwrap_or(default_consistency);
The prepared statement will have exactly the same config as the original query object, so there is no need to calculate serial consistency again.

2023-09-01 11:45 UTC, piodul reviewed
Apart from moving the preparation into `Connection::query`, we will also have to handle batches... Batches can consist of multiple statements, both prepared and unprepared. I guess we have to update `Connection::batch` as well to handle unprepared statements with arguments. We can start with preparing them sequentially in that function, or with some low (fixed?) concurrency.

2023-09-01 13:09 UTC, sylwiaszunejko commented on scylla/src/transport/session.rs
> +                        }
So maybe we should call `prepare` in `Connection::query_with_consistency`, because both `Session::query` and `Connection::query` use that.

2023-09-07 08:40 UTC, piodul approved these changes

2023-09-07 08:41 UTC, merged