Add info about Cargo.lock.msrv to Contributing.md
scylladb/scylla-rust-driver pull request #913
Opened 2024-01-14 18:58 UTC by Lorak-mmk

This is so that contributors (external or internal) are able to find information about how to deal with failures in min_rust CI job.

## Pre-review checklist

- [ ] I have split my patch into logically separate commits.
- [ ] All commit messages clearly explain what they change and why.
- [ ] I added relevant tests for new features and bug fixes.
- [ ] All commits compile, pass static checks and pass test.
- [ ] PR description sums up the changes and reasons why they should be introduced.
- [ ] I have provided docstrings for the public items that I want to introduce.
- [ ] I have adjusted the documentation in `./docs/source/`.
- [ ] I added appropriate `Fixes:` annotations to PR description.

2024-01-19 09:01 UTC, piodul requested changes

2024-01-22 17:11 UTC, Lorak-mmk commented on CONTRIBUTING.md
> +We could pin versions of problematic crates in Cargo.toml, but it would affect version selection
Added backticks to all filenames

2024-01-22 17:12 UTC, Lorak-mmk commented
v2:
- Addressed review comments
- Unrelated small change: removed unnecessary backtick, as it was breaking syntax highlighting

2024-01-24 10:55 UTC, piodul approved these changes

2024-01-24 10:55 UTC, merged